=== govlawtech/dva-sop-api/data/veaServiceReferenceData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="veaServiceReferenceData" type="veaServiceReferenceDataType"/>

  <xs:complexType name="veaServiceReferenceDataType">
    <xs:sequence>
      <xs:element type="warlikeAndNonWarlikeType" name="warlikeAndNonWarlike"/>
      <xs:element type="hazardousType" name="hazardous"/>
      <xs:element type="peacekeepingType" name="peacekeeping"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="warlikeDeterminationsType">
    <xs:sequence>
      <xs:element type="determinationType" name="determination" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="qualificationsType">
    <xs:sequence>
      <xs:element type="xs:string" name="qualification" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="non-warlikeDeterminationsType">
    <xs:sequence>
      <xs:element type="determinationType" name="determination" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="specifiedAreasType">
    <xs:sequence>
      <xs:element type="xs:string" name="specifiedArea" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="specifiedArea">
    <xs:sequence>

      <xs:element type="xs:string" name="specifiedArea" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="operationsType">
    <xs:sequence>
      <xs:element type="operationType" name="operation" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="hazardousType">
    <xs:sequence>
      <xs:element type="xs:string" name="veaLegislativeReference"/>
      <xs:element type="determinationsType" name="determinations"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="peacekeepingType">
    <xs:sequence>
      <xs:element type="xs:complexType" name="veaSch3"/>
      <xs:element type="peacekeepingNoticesType" name="notices"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="veaSch3">
    <xs:sequence>
      <xs:element type="xs:string" name="veaLegislativeReference"/>
      <xs:element type="itemsType" name="items"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="itemsType">
    <xs:sequence>
      <xs:element type="itemType" name="item" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element type="xs:int" name="number"/>
      <xs:element type="xs:string" name="descriptionOfPeacekeepingForce"/>
      <xs:element type="xs:date" name="initialDateAsAPeaceKeepingForce"/>
      <xs:element type="mappingsType" name="mappings" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="mappingsType">
    <xs:sequence>
      <xs:element type="mappingType" name="mapping" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="mappingType">
    <xs:attribute name="regex" type="xs:string"/>
  </xs:complexType>


  <xs:complexType name="warlikeAndNonWarlikeType">
    <xs:sequence>
      <xs:element type="xs:string" name="veaLegislativeReference"/>
      <xs:element type="xs:string" name="description"/>
      <xs:element type="warlikeDeterminationsType" name="warlikeDeterminations"/>
      <xs:element type="non-warlikeDeterminationsType" name="non-warlikeDeterminations"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="operationType">
    <xs:all>
      <xs:element type="xs:string" name="name" minOccurs="1"/>
      <xs:element type="qualificationsType" name="qualifications" minOccurs="0"/>
      <xs:element type="specifiedAreasType" name="specifiedAreas" minOccurs="0"/>
      <xs:element type="xs:date" name="startDate" minOccurs="1"/>
      <xs:element type="xs:date" name="endDate" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="activitiesType">
   <xs:sequence>
     <xs:element type="activityType" name="activity" minOccurs="1"/>
   </xs:sequence>
  </xs:complexType>

  <xs:complexType name="activityType">
    <xs:all>
    <xs:element type="xs:date" name="startDate" minOccurs="1"/>
    <xs:element type="xs:date" name="endDate" minOccurs="0"/>
    <xs:element type="qualificationsType" name="qualifications" minOccurs="0"/>
    <xs:element type="specifiedAreasType" name="specifiedAreas" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="determinationsType">
    <xs:sequence>
      <xs:element type="determinationType" name="determination" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="determinationType">
    <xs:all>
      <xs:element type="xs:string" name="federalRegisterOfLegislationReference"/>
      <xs:element type="xs:date" name="commencementDate"/>
      <xs:element type="operationsType" name="operations" minOccurs="0"/>
      <xs:element type="activitiesType" name="activities" minOccurs="0"/>

      <xs:element type="xs:date" name="startDate" minOccurs="0"/>
      <xs:element type="xs:date" name="endDate" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  
  <xs:complexType name="peacekeepingNoticesType">
    <xs:sequence>
      <xs:element type="xs:string" name="veaLegislativeReference"/>
      <xs:element type="peacekeepingNoticeType" name="notice" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

<xs:complexType name="peacekeepingNoticeType" >
  <xs:all>
    <xs:element type="xs:string" name="legalSource"/>
    <xs:element type="xs:string" name="descriptionOfPeacekeepingForce"/>
    <xs:element type="xs:string" name="shortName"/>
    <xs:element type="xs:date" name="initialDateAsAPeaceKeepingForce"/>
    <xs:element type="mappingsType" name="mappings"/>
  </xs:all>
</xs:complexType>
</xs:schema>

=== govlawtech/dva-sop-api/data/veaServiceReferenceData.xml
<?xml version="1.0" encoding="UTF-8" ?>

<veaServiceReferenceData
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="veaServiceReferenceData.xsd">
    <warlikeAndNonWarlike>

        <veaLegislativeReference>6F</veaLegislativeReference>
        <description>Operational service—warlike and non‑warlike service</description>

        <warlikeDeterminations>
        
            
            <determination>
                <federalRegisterOfLegislationReference>F2009L02442</federalRegisterOfLegislationReference>
                <commencementDate>2008-07-21</commencementDate>
                <operations>
                    <operation>
                        <name>RIVERBANK</name>
                        <startDate>2008-07-21</startDate>
                        <qualifications>
                            <qualification>service with the Australian Defence Force contribution to the United Nations Assistance Mission in Iraq</qualification>
                        </qualifications>
                        <specifiedAreas>
                            <specifiedArea>Iraq</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2006B00960</federalRegisterOfLegislationReference>
                <commencementDate>2003-09-16</commencementDate>
                <operations>
                    <operation>
                        <name>FALCONER</name>
                        <startDate>2003-03-18</startDate>
                        <endDate>2003-07-22</endDate>
                        <specifiedAreas>
                            <specifiedArea>The area bounded by the geographical coordinates: 38 00N, 68 00E; 38 00N, 32 00E; 10 00N, 32 00E; 10 00N, 68 00E.
                            </specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2010L00699</federalRegisterOfLegislationReference>
                <commencementDate>2010-02-12</commencementDate>
                <operations>
                    <operation>
                        <name>CATALYST</name>
                        <startDate>2003-07-16</startDate>
                        <endDate>2009-07-31</endDate>
                        <specifiedAreas>
                            <specifiedArea>Iraq, territorial waters and adjacent airspace</specifiedArea>
                            <specifiedArea>Kuwait, territorial waters and adjacent airspace</specifiedArea>
                            <specifiedArea>Bahrain, territorial waters and adjacent airspace</specifiedArea>
                            <specifiedArea>Qatar, territorial waters and adjacent airspace</specifiedArea>
                            <specifiedArea>United Arab Emirates, territorial waters and adjacent airspace</specifiedArea>
                            <specifiedArea>Saudia Arabia, territorial waters and adjacent airspace north of 23 degrees North latitude</specifiedArea>
                            <specifiedArea>the Persian Gulf</specifiedArea>
                            <specifiedArea>the Straight of Hormuz</specifiedArea>


                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2006B00579</federalRegisterOfLegislationReference>
                <commencementDate>2003-09-16</commencementDate>
                <operations>
                    <operation>
                        <name>CITADEL</name>
                        <startDate>2002-05-20</startDate>
                        <endDate>2003-08-17</endDate>
                        <specifiedAreas>
                            <specifiedArea>East Timor</specifiedArea>
                            <specifiedArea>the territorial sea of East Timor</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2006B00577</federalRegisterOfLegislationReference>
                <commencementDate>2004-04-01</commencementDate>
                <operations>
                    <operation>
                        <name>TANAGER</name>
                        <startDate>2000-02-20</startDate>
                        <endDate>2002-05-19</endDate>
                        <specifiedAreas>
                            <specifiedArea>East Timor</specifiedArea>
                            <specifiedArea>the territorial sea of East Timor</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2006B00578</federalRegisterOfLegislationReference>
                <commencementDate>2000-06-21</commencementDate>
                <operations>
                    <operation>
                        <name>WARDEN</name>
                        <startDate>1999-09-16</startDate>
                        <endDate>2000-04-10</endDate>
                        <specifiedAreas>
                            <specifiedArea>East Timor</specifiedArea>
                            <specifiedArea>the sea area that on 16 September 1999 was the territorial sea of Indonesia adjacent to East Timor</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            
            <determination>
                <federalRegisterOfLegislationReference>F2005L03487</federalRegisterOfLegislationReference>
                <commencementDate>2005-10-31</commencementDate>
                <operations>
                    <operation>
                        <name>PALATE</name>
                        <startDate>2003-04-18</startDate>
                        <endDate>2004-06-30</endDate>
                        <specifiedAreas>
                            <specifiedArea>Afghanistan</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2009L00722</federalRegisterOfLegislationReference>
                <commencementDate>2009-01-01</commencementDate>
                <operations>
                    <operation>
                        <name>KRUGER</name>
                        <startDate>2009-01-01</startDate>
                        <specifiedAreas>
                            <specifiedArea>Iraq</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2006B00958</federalRegisterOfLegislationReference>
                <commencementDate>2000-06-21</commencementDate>
                <operations>
                    <operation>
                        <name>FABER</name>
                        <startDate>1999-09-16</startDate>
                        <endDate>2000-02-23</endDate>
                        <specifiedAreas>
                            <specifiedArea>East Timor</specifiedArea>
                            <specifiedArea>the sea area that on 16 September 1999 was the territorial sea of Indonesia adjacent to East Timor</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>

            <determination>
                <federalRegisterOfLegislationReference>F2006L01121</federalRegisterOfLegislationReference>
                <commencementDate>2006-02-13</commencementDate>
                <operations>
                    <operation>
                        <name>TAMAR</name>
                        <startDate>1994-07-25</startDate>
                        <endDate>1996-02-16</endDate>
                        <specifiedAreas>
                            <specifiedArea>Rwanda</specifiedArea>
                            <specifiedArea>the areas in Uganda, Zaire (now known as the Democratic Republic of the Congo), Burundi and Tanzania that are not more than 50 kilometres from the border with Rwanda</specifiedArea>
                        </specifiedAreas>
                    </operation>

                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2007L04375</federalRegisterOfLegislationReference>
                <commencementDate>2007-04-16</commencementDate>
                <operations>
                    <operation>
                        <name>JURAL</name>
                        <startDate>1991-06-30</startDate>
                        <endDate>2003-01-12</endDate>
                        <qualifications>
                            <qualification>with the United Kingdom elements of the coalition force operation to patrol the Iraq No-Fly-Zones</qualification>
                        </qualifications>
                        <specifiedAreas>
                            <specifiedArea>Iraq</specifiedArea>
                        </specifiedAreas>
                    </operation>
                </operations>
            </determination>
            
            <determination>
                <federalRegisterOfLegislationReference>F2007L00986</federalRegisterOfLegislationReference>
